---
title: Vyral Creative Services
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: bryce@getvyral.com
description: Our Creative Services - Vyral Marketing
baseurl: ''
url: localhost:4000
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
gems:
- jemoji
exclude:
- node_modules
sass:
  sass_dir: _sass
  style: :nested
